package TerraBlocks;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

////////////////////////////////////////////////////////////////////////////
///        @author Gustaf Franzén :: https://github.com/BjorneEk;        ///
////////////////////////////////////////////////////////////////////////////

public class Settings extends javax.swing.JPanel {

	/**
	 * Creates new form Settings
	 */
	private TerraBlocks ctx;

	public Settings(TerraBlocks ctx) {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		savebtn = new javax.swing.JButton();
		lbl     = new javax.swing.JLabel();

		setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

		savebtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
		savebtn.setText("Save");
		savebtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				savebtnActionPerformed(evt);
			}
		});

		lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
		lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbl.setText("Settings");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addGap(55, 55, 55)
						.addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup()
						.addGap(110, 110, 110)
						.addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(72, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				.addGap(51, 51, 51)
				.addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
				.addComponent(savebtn)
				.addGap(105, 105, 105))
		);
	}// </editor-fold>//GEN-END:initComponents

	private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed

		try {
			ctx.save();
		} catch (IOException ex) {
			Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
		}

	}//GEN-LAST:event_savebtnActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel lbl;
	private javax.swing.JButton savebtn;
	// End of variables declaration//GEN-END:variables
}
