package TerraBlocks;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JPanel;


////////////////////////////////////////////////////////////////////////////
///        @author Gustaf Franzén :: https://github.com/BjorneEk;        ///
////////////////////////////////////////////////////////////////////////////

///
/// JPanel with the launcher components
///

public class StartMenu extends javax.swing.JPanel {

	/**
	 * Creates new form StartMenu
	 */
	public static final java.awt.Cursor cursor      = new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR);
	private static final BufferedImage cursorImg    = new BufferedImage(16, 16, BufferedImage.TYPE_INT_ARGB);
	public static final java.awt.Cursor blankCursor = Toolkit.getDefaultToolkit().createCustomCursor(cursorImg, new Point(0, 0), "blank cursor");
	private static boolean blank                    = true;

	BufferedImage background;
	Game g;

	public StartMenu() {
		int w;
		int h;
		BufferedImage     after = null;
		AffineTransform   at    = new AffineTransform();
		AffineTransformOp scaleOp;
		//this.setSize(1080, 1920);
		initComponents();
		try {
			background = ImageIO.read(new File("src/Assets/startmenu.png"));
			w = background.getWidth();
			h = background.getHeight();
			after = new BufferedImage(w*4, h*4, BufferedImage.TYPE_INT_ARGB);
			at.scale(3.3, 3.7);
			scaleOp = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
			after = scaleOp.filter(background, after);
			background = after;
		} catch (IOException e) {
		}
	}

	@Override
	public void paintComponent(Graphics g) {
		super.paintComponent(g);
		g.setColor(Color.GREEN);
		g.fillRect(0, 0, super.getWidth(),super.getHeight());
		g.drawImage(background, 0, 0, null);
		g.setColor(Color.BLACK);
		Font f = new Font("Dialog", Font.BOLD, 100);
		g.setFont(f);
		g.drawString("TerraBlocks!" ,(super.getWidth() / 2)-300, 250);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 1719, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 1028, Short.MAX_VALUE)
		);
	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables
}
